main: cn.wode490390.nukkit.scatteredbuilding.ScatteredBuildingPopulator
name: "ScatteredBuildingPopulator"
description: "Scattered building populator plugin for Nukkit"
author: "wode490390"
website: "http://wode490390.cn/"
version: "${pom.version}"
api: ["1.0.0"]
load: STARTUP
#softdepend: ["MobPlugin"]
